### ISSUE TITLE
Please add exit option

### ISSUE THREAD

**Issue by Mr-Negative** [bencmbrook/bpm#1]
It would be nice to add right click menu with exit option.

**Comment by bencmbrook** [comment]
Agreed. I think I'll add right click as well as any button held down + click to quit. Will do that now!

**Comment by Mr-Negative** [comment]
Nice.

**Comment by spencercap** [comment]
Agreed, has this happened?

**Comment by bencmbrook** [comment]
Exit option has been added. (control-click to quit).
Please grab the update here: [http://www.builtbybenbrook.com/assets/downloads/bpm.zip](http://www.builtbybenbrook.com/assets/downloads/bpm.zip)
