### ISSUE TITLE
bmp reading is inaccurate

### ISSUE THREAD

**Issue by iamredbeard** [bencmbrook/bpm#2]
when ticking the bmp is varies even in 50+ bpm ....I was running a 4 bar loop at 122bpm. 

It would be good to have an on-off feature to keep the bpm app running so it can become more accurate by adapting the reading instead of relying on clicks.

**Comment by bencmbrook** [comment]
It is a bpm _tapper_, so it is not listening to the audio you are playing (at least for now!). Rather, you click the button repeatedly at the tempo and it will provide you with a reading.
